spring:
  application:
    name: PLATFORM #服务名称
  datasource:
    url: jdbc:mysql://122.51.247.67:3306/crm?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8102 #运行端口号
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
  httpclient:
    enabled: true
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 1 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://122.51.247.67:8001/eureka/  #配置注册中心地址
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml